{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Power plus",
    "description": "backend for react app Power plus"
  },
  "servers": [
    {
      "url": "https://teamproject-powerpulse-group4.onrender.com/"
    }
  ],
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "parameters": {
      "Authorization": {
        "name": "Authorization",
        "in": "header",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "Bearer Token"
      }
    }
  },
  "tags": [
    {
      "name": "Identification",
      "description": "User endpoints"
    },
    {
      "name": "Products",
      "description": "Products endpoints"
    },
    {
      "name": "Exercises",
      "description": "Exercises endpoints"
    },
    {
      "name": "Diary",
      "description": "Diary endpoints"
    },
    {
      "name": "Statistics",
      "description": "Statistics endpoints"
    }
  ],
  "paths": {
    "/identification/signup": {
      "post": {
        "tags": ["Identification"],
        "summary": " user signup",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "12233test@gmail.com",
                "password": "ivasukTelesuk",
                "name": "Ivasuk"
              }
            }
          },
          "description": "`name` - string, required.`email` - string email required.`password` - string, min 6, required."
        },
        "responses": {
          "200": {
            "description": "successful signup",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "client": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        }
                      }
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "client": {
                    "email": "12233test@gmail.com",
                    "name": "Ivasuk"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZjVlN2YwYzIxNjA5Yzc5M2NjY2YiLCJpYXQiOjE2OTgxNjYyNDcsImV4cCI6MTY5ODIzODI0N30.mKzizoialddNQG5OSXoEfvfoXtp38fZuyvbxdwwbQVw"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/identification/login": {
      "post": {
        "tags": ["Identification"],
        "summary": "user login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "1223test@gmail.com",
                "password": "test@gmail.com"
              }
            }
          },
          "description": "`email` - string email required.`password` - string, min 6, required."
        },
        "responses": {
          "200": {
            "description": "successful login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "client": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "_id": {
                          "type": "string"
                        },
                        "_v": {
                          "type": "number"
                        }
                      }
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "client": {
                    "_id": "6537dcf0ab10068d0d3e9897",
                    "email": "1223test@gmail.com",
                    "name": "mymykola",
                    "__v": 0,
                    "BMR": 2170,
                    "birthday": "2003-10-10T00:00:00.000Z",
                    "blood": 4,
                    "currentWeight": 55,
                    "desiredWeight": 55,
                    "height": 155,
                    "levelActivity": 4,
                    "sex": "male",
                    "timeForSport": 110
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZGNmMGFiMTAwNjhkMGQzZTk4OTciLCJpYXQiOjE2OTgxNjU3ODUsImV4cCI6MTY5ODIzNzc4NX0.2113-G0zi1aO2HyHcgLPoKo7ht_l47nW1omoUw6DyYA"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/identification/calculateDailyMetrics": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Identification"],
        "summary": "count BMR",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "height": {
                    "type": "number"
                  },
                  "currentWeight": {
                    "type": "number"
                  },
                  "desiredWeight": {
                    "type": "number"
                  },
                  "birthday": {
                    "type": "string",
                    "format": "date",
                    "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                  },
                  "blood": {
                    "type": "number"
                  },
                  "sex": {
                    "type": "string"
                  },
                  "levelActivity": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "birthday": "2003-10-10",
                "blood": 4,
                "currentWeight": 55,
                "desiredWeight": 55,
                "height": 155,
                "levelActivity": 4,
                "sex": "male"
              }
            }
          },
          "description": "`height` - number; minimum 150; required .`currentWeight` - number; minimum 35; required .`desiredWeight` - number; minimum 35; required .`birthday` - date; must be older than 18 ;  required .`blood` - number; allowed values 1, 2, 3, 4; required .`sex` - string; allowed values 'male', 'female'; required .`levelActivity` - number; allowed values 1, 2, 3, 4, 5; required"
        },
        "responses": {
          "200": {
            "description": "calculated BMR an avatar can also be displayed if there is one",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "client": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "_id": {
                          "type": "string"
                        },
                        "_v": {
                          "type": "number"
                        },
                        "height": {
                          "type": "number"
                        },
                        "currentWeight": {
                          "type": "number"
                        },
                        "desiredWeight": {
                          "type": "number"
                        },
                        "birthday": {
                          "type": "string",
                          "format": "date",
                          "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                        },
                        "blood": {
                          "type": "number"
                        },
                        "sex": {
                          "type": "string"
                        },
                        "levelActivity": {
                          "type": "number"
                        },
                        "BMR": {
                          "type": "number"
                        },
                        "timeForSport": {
                          "type": "number"
                        }
                      }
                    }
                  },
                  "example": {
                    "client": {
                      "_id": "6537dcf0ab10068d0d3e9897",
                      "email": "1223test@gmail.com",
                      "name": "mymykola",
                      "__v": 0,
                      "BMR": 2170,
                      "birthday": "2003-10-10T00:00:00.000Z",
                      "blood": 4,
                      "currentWeight": 55,
                      "desiredWeight": 55,
                      "height": 155,
                      "levelActivity": 4,
                      "sex": "male",
                      "timeForSport": 110
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/identification/upload": {
      "patch": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Identification"],
        "summary": "upload name or avatar",
        "description": "`avatar`:{body:form-data,key:avatar,file:superAvatarka .jpg||.png} or  `name`:change name",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            },
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "update name or avatar",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "object": null
                    },
                    "properties": {
                      "message": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Не знайдено",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/identification/currentUser": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Identification"],
        "summary": "get current user",
        "responses": {
          "200": {
            "description": "current user an avatar can also be displayed if there is one",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "client": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "_id": {
                          "type": "string"
                        },
                        "_v": {
                          "type": "number"
                        },
                        "height": {
                          "type": "number"
                        },
                        "currentWeight": {
                          "type": "number"
                        },
                        "desiredWeight": {
                          "type": "number"
                        },
                        "birthday": {
                          "type": "string"
                        },
                        "blood": {
                          "type": "number"
                        },
                        "sex": {
                          "type": "string"
                        },
                        "levelActivity": {
                          "type": "number"
                        },
                        "BMR": {
                          "type": "number"
                        },
                        "timeForSport": {
                          "type": "number"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Не знайдено",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/identification/logout": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Identification"],
        "summary": "logout user",
        "responses": {
          "200": {
            "description": "logout user"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Products"],
        "summary": "Get list of products",
        "description": "Returns a list of all products",
        "responses": {
          "200": {
            "description": "A list of products",
            "content": {
              "application/json": {
                "example": "[{\"_id\":\"12345\", \"weight\":\"100\", \"calories\":\"340\", \"category\":\"diary\",  \"title\":\"Danbo cheese\", \"groupBloodNotAllowed\":{\"1\":\"true\",\"2\":\"true\",\"3\":\"true\",\"4\":\"true\"}}]",
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "weight": {
                        "type": "string"
                      },
                      "calories": {
                        "type": "string"
                      },
                      "category": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "groupBloodNotAllowed": {
                        "type": "object",
                        "properties": {
                          "1": {
                            "type": "string"
                          },
                          "2": {
                            "type": "string"
                          },
                          "3": {
                            "type": "string"
                          },
                          "4": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/available-blood-products/{type}": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Products"],
        "summary": "Get list of available products by blood type",
        "description": "Returns a list of all available products according to blood what indicated in client data, {type} must be \"true\" or \"false\" ",

        "parameters": [
          {
            "name": "type",
            "in": "path",
            "description": "Available for blood",
            "required": true,
            "schema": {
              "type": "string",
              "enum": ["true", "false"]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A list of products",
            "content": {
              "application/json": {
                "example": "[{\"_id\":\"12345\", \"weight\":\"100\", \"calories\":\"340\", \"category\":\"diary\",  \"title\":\"Danbo cheese\", \"groupBloodNotAllowed\":{\"1\":\"true\",\"2\":\"true\",\"3\":\"true\",\"4\":\"true\"}}]",
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "weight": {
                        "type": "string"
                      },
                      "calories": {
                        "type": "string"
                      },
                      "category": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "groupBloodNotAllowed": {
                        "type": "object",
                        "properties": {
                          "1": {
                            "type": "string"
                          },
                          "2": {
                            "type": "string"
                          },
                          "3": {
                            "type": "string"
                          },
                          "4": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/categories": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Products"],
        "summary": "Get list of products categories",
        "description": "Returns a list of all products categories",
        "responses": {
          "200": {
            "description": "A list of products categories",
            "content": {
              "application/json": {
                "example": "[{\"_id\":\"12345\", \"name\":\"productsCategories\", \"items\":[\"alcoholic drinks\",\"berries\"]}]",
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/exercises/{type}": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Exercises"],
        "summary": "returns filtered exercises by type",
        "description": "`type`:body part || equipment || Muscles . one of these values",
        "responses": {
          "200": {
            "description": "A list of exersices",
            "content": {
              "application/json": {
                "example": "[{\"_id\":\"12345\", \"bodyPart\":\"chest\", \"equipment\":\"leverage machine\", \"gifUrl\":\"https://ftp.goit.study/img/power-pulse/gifs/0009.gif\", \"name\":\"assisted chest dip (kneeling)\", \"target\":\"pectorals\", \"burnedCalories\":329, \"time\":3}]",
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "bodyPart": {
                        "type": "string"
                      },
                      "equipment": {
                        "type": "string"
                      },
                      "gifUrl": {
                        "type": "string"
                      },
                      "target": {
                        "type": "string"
                      },
                      "burnedCalories": {
                        "type": "integer"
                      },
                      "time": {
                        "type": "integer"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/exercises/all-types": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Exercises"],
        "summary": "Get list of bodyparts, muscules, equipments",
        "description": "Returns a list of all bodyparts, muscules, equipments",
        "responses": {
          "200": {
            "description": "A list of users",
            "content": {
              "application/json": {
                "example": "{\"bodyParts\":[\"_id:650f35ece3f5522fc639628a,filter:Body parts,name:cardio,imgURL:https://ftp.goit.study/img/power-pulse/filters/cardio_pkkceg.jpg\",\"upper legs\"], \"equipment\":[\"\"_id:650f35ece3f5522fc639628a,filter:equipment,name:cardio,imgURL:https://ftp.goit.study/img/power-pulse/filters/cardio_pkkceg.jpg\"], \"muscules\":[\"_id:650f35ece3f5522fc639628a,filter:muscules,name:cardio,imgURL:https://ftp.goit.study/img/power-pulse/filters/cardio_pkkceg.jpg\",\"upper legs\"]}",
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/diary/save-product": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Diary"],
        "summary": "Save product",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  },
                  "calories": {
                    "type": "number"
                  }
                },
                "required": ["product", "amount", "calories"],
                "example": {
                  "product": "5d51694902b2373622ff5773",
                  "amount": 250,
                  "calories": 100
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Save diary product",
            "content": {
              "application/json": {
                "example": {
                  "message": "product was add"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/diary/save-exercise": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "summary": "save exercise",
        "tags": ["Diary"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "exercise": {
                    "type": "string"
                  },
                  "time": {
                    "type": "number"
                  },
                  "calories": {
                    "type": "number"
                  }
                },
                "required": ["exercise", "time", "calories"],
                "example": {
                  "exercise": "64f2458d6f67bc34bae4f7f7",
                  "time": 22,
                  "calories": 100
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Save exercise",
            "content": {
              "application/json": {
                "example": {
                  "message": "exercise was add"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/diary/delete-exercise/{exerciseId}": {
      "delete": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Diary"],
        "summary": "delete exercise",
        "parameters": [
          {
            "name": "Exercise Id",
            "in": "path",
            "description": "Type exercise ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "delete exercise",
            "content": {
              "application/json": {
                "example": {
                  "message": "exercise was delete"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/diary/delete-product/{productId}": {
      "delete": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Diary"],
        "summary": "Delete product",
        "parameters": [
          {
            "name": "Product Id",
            "in": "path",
            "description": "Type product ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "delete product",
            "content": {
              "application/json": {
                "example": {
                  "message": "product was delete"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/diary/diary-date-info/{date}": {
      "get": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "tags": ["Diary"],
        "summary": "receive the products and are entitled to the selected date as we are given as an option",
        "parameters": [
          {
            "name": "Date",
            "in": "path",
            "description": "Type a date",
            "example": "2003-10-10",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "receive the products and are entitled to the selected date as we are given as an option",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "diary": {
                      "type": "object",
                      "properties": {
                        "_id": {
                          "type": "string"
                        },
                        "clientId": {
                          "type": "string"
                        },
                        "__v": {
                          "type": "number"
                        },
                        "consumedProduct": {
                          "type": "array"
                        },
                        "exerciseDone": {
                          "type": "array"
                        }
                      },
                      "example": {
                        "_id": "65382f75584555dfbc2cfb16",
                        "clientId": "653567572c6e5ea5140c44a7",
                        "__v": 0,
                        "consumedProduct": [],
                        "exerciseDone": []
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/statistics": {
      "get": {
        "tags": ["Statistics"],
        "summary": "Get info statistics",
        "description": "Returns a list of all counts of trainings, burned calories, registered users, spent time of all users, total users made exercises",
        "responses": {
          "200": {
            "description": "A list statictics data",
            "content": {
              "application/json": {
                "example": "{\"trainingsQuantity\":\"1324\", \"burnedAllUsersCalories\":\"800\", \"registeredUsersCount\":\"27\", \"spentAllUsersTime\":\"622\", \"totalUsersExercisesCount\":\"4\"}",
                "schema": {
                  "type": "object",
                  "properties": {
                    "trainingsQuantity": {
                      "type": "number"
                    },
                    "burnedAllUsersCalories": {
                      "type": "number"
                    },
                    "registeredUsersCount": {
                      "type": "number"
                    },
                    "spentAllUsersTime": {
                      "type": "number"
                    },
                    "totalUsersExercisesCount": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "message": "Not found"
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
